### ISSUE TITLE
Is it possible to use the nodes GPU?

### ISSUE THREAD

**Issue by 2010019970909** [ray-project/xgboost_ray#1]
Hello,

I'm quite new to the use of clusters, etc. and I was wondering if this version of XGBoost was also integrating a multi GPU distribution layout over the cluster's nodes. I must use slurm to manage my jobs, so I can request a number of nodes with a number of GPU per node, etc. But I don't know if it's more interresting to use one node with x amount of GPUs or N nodes with Ny CPU and Nx GPU, etc.

So as in the title: "Is it possible to use the nodes GPU?". And if so, how?

Have a nice day,
Vincent

**Comment by richardliaw** [comment]
Hi @2010019970909, we have preliminary support for this by setting:

```
bst = train(
    {..., "tree_method": "gpu_hist"},
    num_gpus_per_worker=1
)
```

**Comment by krfricke** [comment]
Hi @2010019970909,

as Richard pointed out we support GPU usage by the usual means of XGBoost (i.e. setting `tree_method="gpu_hist"` in the parameters).

This does work with distributed workers, too. 

Working with more than one GPU per node should work out of the box, too (by setting `num_gpus_per_worker=1`). Which method you prefer depends a bit on the size of your training job, node stability, and dataset. I'd suggest going with more workers on smaller machines first, except when you're training on very large setups (say, > 32 GPUs). 

I'll close this issue for now, but please do let us know if you need help with the setup or have any other questions. We are more than happy to help you be successful with distributed GPU training, as we were planning be looking into this more thoroughly in the coming weeks anyway.

**Comment by 2010019970909** [comment]
Hi @krfricke,

I should have closed this ticket before. My usecase did slightly change and the training on the dataset we are using is taking roughly 5 minutes on one node with 3 GPUs (one P100, and two 1080 Ti). Also, I only have two nodes available so it's less interesting for the moment. I'll continue to use XGBoost on this same project next year, with maybe more data (so I might take a look at further 'parallelisation' in the future). Thank for your replies @richardliaw and @krfricke.

Regards,
Vincent
