### ISSUE TITLE
Add support for `groups` param for ranking to `RayDMatrix`

### ISSUE THREAD

**Issue by Yard1** [ray-project/xgboost_ray#119]
`groups` in `DMatrix` cannot be currently set, limiting ranking functionality. Should be added at some point.

**Comment by krfricke** [comment]
cc @mmui

**Comment by heyitsmui** [comment]
starting to look into this today

**Comment by heyitsmui** [comment]
This should be addressed in https://github.com/ray-project/xgboost_ray/pull/239 with @atomic

**Comment by heyitsmui** [comment]
@Yard1 i believe we can close this
