### ISSUE TITLE
Tune Integration Improvements

### ISSUE THREAD

**Issue by amogkam** [ray-project/xgboost_ray#18]
There are 2 main improvements that need to be made to the current Tune Integration

**Better Resources API**
Currently setting `extra_cpu` in trial resources is not a good user experience and exposes too much of the internal implementation to the user. We should implement a better API for this. A few options:
1) Similar to SGD, we use the Trainable class API which will automatically handle the setting of resources
2) Add a utility function which will automatically return the resources dict given the ray_train args

**Add support for intermediate checkpointing to Tune**
Currently tune.report callback is supported, but we need to add checkpointing with Tune as well to support schedulers like PBT.

**Comment by richardliaw** [comment]
(also colocation of workers, as mentioned offline)

**Comment by amogkam** [comment]
These should all be resolved now.
