### ISSUE TITLE
Difference in predictions b/w Original XGBRanker & Ray XGBRanker

### ISSUE THREAD

**Issue by ramab1988** [ray-project/xgboost_ray#188]
Hi!

I was testing whether Original XGBRanker & Ray XGBRanker give the same predictions or not for a given dataset with all the hyperparameters fixed b/w both. However, I am getting different results. Should we get the same results?? Please correct me if I am wrong here.

Adding code to reproduce the same.

`Data preparation`
```python
from xgboost_ray import RayXGBRanker, RayParams
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import numpy as np

seed = 42

X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
   X, y, train_size=0.1, random_state=42
)

# This is done just to get random relevant values for ranker
y_train = np.random.rand(len(y_train))
group_train=np.array([20, 10, 26])
y_train
```

`Original XGBRanker`
```python
import xgboost as xgb

model = xgb.XGBRanker(  
    booster="gbtree",
    objective="rank:pairwise",
    random_state=seed,
    learning_rate=0.1,
    colsample_bytree=0.9,
    eta=0.05,
    max_depth=6,
    n_estimators=10, 
    subsample=0.75
    )

model.fit(X_train,
          y_train,
          group=group_train,
          eval_metric = "ndcg",
          verbose=True)

pred_xgb = list(model.predict(X_test[:10]))
print(pred_xgb)
```

`[0.15773186, 0.4373201, -0.018760577, 0.43370134, 0.46030942, 0.4633737, 0.61562264, 0.6771464, 0.6505353, 0.7690198]`

`Ray XGBRanker`
```python


clf = RayXGBRanker(
    n_jobs=2,
    booster="gbtree",
    objective="rank:pairwise",
    random_state=seed,
    learning_rate=0.1,
    colsample_bytree=0.9,
    eta=0.05,
    max_depth=6,
    n_estimators=10, 
    subsample=0.75
)
clf.fit(X_train, 
        y_train, 
        group=group_train, 
        ray_dmatrix_params={}, 
        eval_metric = "ndcg",
        verbose=True)
pred_ray = clf.predict(X_test[:10])
print(pred_ray)
```

`[0.5214866  0.6265878  0.5315001  0.3475427  0.02021255 0.86146027
 0.7941384  0.69921595 0.17514387 0.62002087]`

I think this is closely related to [this issue](https://github.com/ray-project/xgboost_ray/issues/186). 

Also, predictions made by `XGBClassifier` and `RayXGBClassifier` are also not matching with each other. So, thought of raising this issue. 

Thanks,
Rama

**Comment by Yard1** [comment]
This is currently being worked on! We should have a fix in under a week. Same issue as in https://github.com/ray-project/xgboost_ray/issues/186

**Comment by ramab1988** [comment]
Sure. Basically, instead of XGBRanker, I tried out XGBClassifier to see if the predicted probabilities match.

Please have a look at the following piece of code.

`Data preparation`
```python
from xgboost_ray import RayXGBClassifier, RayParams
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import numpy as np

seed = 42

X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
   X, y, train_size=0.3, random_state=42
)

y_train
```

`Original XGBClassifier`
```python
import xgboost as xgb

model = xgb.XGBClassifier(  
    booster="gbtree",
    objective="binary:logistic",
    random_state=seed,
    learning_rate=0.1,
    colsample_bytree=0.9,
    eta=0.05,
    max_depth=3,
    n_estimators=10, 
    subsample=0.75
    )

model.fit(X_train,
          y_train,
          eval_metric = "logloss",
          verbose=True)

pred_xgb = model.predict_proba(X_test[:10])
print(pred_xgb)
```
`[[0.22923529 0.7707647 ]
 [0.8040637  0.19593629]
 [0.8040637  0.19593629]
 [0.1936959  0.8063041 ]
 [0.1893403  0.8106597 ]
 [0.8040637  0.19593629]
 [0.8040637  0.19593629]
 [0.70779985 0.29220015]
 [0.66134006 0.33865994]
 [0.1893403  0.8106597 ]]`

`Ray XGBClassifier`
```python
clf = RayXGBClassifier(
    n_jobs=2,
    booster="gbtree",
    objective="binary:logistic",
    random_state=seed,
    learning_rate=0.1,
    colsample_bytree=0.9,
    eta=0.05,
    max_depth=3,
    n_estimators=10,
    subsample=0.75
)
clf.fit(X_train, 
        y_train, 
        eval_metric = "logloss",
        verbose=True)

pred_ray = clf.predict_proba(X_test[:10])
print(pred_ray)
```

`[[0.1921137  0.8078863 ]
 [0.76557446 0.23442553]
 [0.8058486  0.19415142]
 [0.1921137  0.8078863 ]
 [0.1921137  0.8078863 ]
 [0.8058486  0.19415142]
 [0.8058486  0.19415142]
 [0.65557957 0.34442046]
 [0.7161065  0.28389353]
 [0.1921137  0.8078863 ]]`

Should we expect almost the same probabilities from both models? 
If yes, am I missing any parameter that is resulting in this discrepancy?

Thanks!
Rama

**Comment by ramab1988** [comment]
Got it. Thanks. 
Closing the issue.
