### ISSUE TITLE
"grpc_message":"Received message larger than max

### ISSUE THREAD

**Issue by cgy-dayup** [ray-project/xgboost_ray#201]
_InactiveRpcError                         Traceback (most recent call last)
<ipython-input-3-42e2982675d4> in <module>
        47     num_samples=1,
        48     scheduler=ASHAScheduler(max_t=200),
---> 49     resources_per_trial=ray_params.get_tune_resources())
        50 print("Best hyperparameters", analysis.best_config)
.....
/usr/local/lib/python3.6/dist-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
       847             return state.response
       848     else:
--> 849           raise _InactiveRpcError(state)
      850 
      851 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (210771146 vs. 104857600)"
	debug_error_string = "{"created":"@1646188124.309444695","description":"Error received from peer ipv4:10.207.183.32:40455","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Received message larger than max (210771146 vs. 104857600)","grpc_status":8}"

**Comment by cgy-dayup** [comment]
when i want to test the demo using my own dataset,i come across the problem?

**Comment by Yard1** [comment]
Are you loading the dataset in a distributed fashion?

**Comment by cgy-dayup** [comment]
> Are you loading the dataset in a distributed fashion? Can you show the entire script?
no,i am not.i load the csv from local.Below is the full script：

import lightgbm as lgb
import numpy as np
import pandas as pd
# import modin.pandas as pd
import datetime
import sklearn.datasets
import sklearn.metrics
from sklearn.model_selection import train_test_split

from ray import tune
from ray.tune.schedulers import ASHAScheduler
from ray.tune.integration.lightgbm import TuneReportCheckpointCallback
from time import *

df_all = pd.read_csv('raytest.csv')

# df_all=df_all[0:50000]
df_all.dropna(how='any',inplace=True)
no_fea_list=['cate_id']
all_data=df_all.drop(no_fea_list,axis=1)
all_data['sale_ord_dt']=pd.to_datetime(all_data.sale_ord_dt)
max_data=all_data.sale_ord_dt.max()
predict_days=7
test_start_date=pd.to_datetime(max_data) + datetime.timedelta(days=(predict_days*-1))
df_train=all_data[all_data.sale_ord_dt<=test_start_date]
df_dev=all_data[(all_data.sale_ord_dt<=max_data)&(all_data.sale_ord_dt>test_start_date)]
df_train=df_train.sample(frac=1)
x_train=df_train.drop(['item_sku_id','sale_ord_dt','gena_sale_qtty'],axis=1)
x_test=df_dev.drop(['item_sku_id','sale_ord_dt','gena_sale_qtty'],axis=1)
y_train=df_train['gena_sale_qtty']
y_test=df_dev['gena_sale_qtty'] 
train_data = lgb.Dataset(x_train, label=y_train)
test_data = lgb.Dataset(x_test, label=y_test)
cat_feature=['big_sale_flag','is_weekday','day_week','week_num',
                                  'mon_num','day_mon','region']
def traindata(config):
    gbm = lgb.train(
        config,
        train_set=train_data,
        valid_sets=[test_data],
        valid_names=["eval"],
        verbose_eval=False,
        categorical_feature=cat_feature
         callbacks=[
             TuneReportCheckpointCallback({
                 "l1": "eval-l1"
             })
         ])
    y_pre=gbm.predict(x_test)
    res=sklearn.metrics.mean_absolute_error(y_pre,y_test)
    tune.report(mean_accuracy=res, done=True)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--server-address",
        type=str,
        default=None,
        required=False,
        help="The address of server to connect to if using "
        "Ray Client.")
    args, _ = parser.parse_known_args()

    if args.server_address:
        import ray

        ray.init(f"ray://{args.server_address}")

    config = {
        "boosting_type": "gbdt",
        'objective': 'regression',
        "metric": "l1",
        "verbose": -1,
        "learning_rate": tune.grid_search([1e-4, 1e-3, 1e-2]),
        "num_boost_round": tune.grid_search([300, 500, 1000]),
        "colsample_bytree": tune.grid_search([0.7, 0.8,1]),
        "max_depth": tune.grid_search([5, 6, 7]),
    }

    analysis = tune.run(
        traindata,
        metric="l1",
        mode="min",
        config=config,
         num_samples=10,
        scheduler=ASHAScheduler(max_t=200)
        )

    print("Best hyperparameters found were: ", analysis.best_config)

**Comment by cgy-dayup** [comment]
> Are you loading the dataset in a distributed fashion? Can you show the entire script?

no,i am not.i load the csv from local.Below is the full script：
`import lightgbm as lgb
import numpy as np
import pandas as pd
# import modin.pandas as pd
import datetime
import sklearn.datasets
import sklearn.metrics
from sklearn.model_selection import train_test_split

from ray import tune
from ray.tune.schedulers import ASHAScheduler
from ray.tune.integration.lightgbm import TuneReportCheckpointCallback
from time import *

def mape(error, y):
        error=error[y!=0]
        y=y[y!=0]
        err=np.abs(error/y)       
        return np.mean(err)
def cal_mape_nation(df_dev):
    if df_dev.dtypes['item_sku_id']=='float':
        df_dev=df_dev.astype({'item_sku_id':'int'})
    df_dev=df_dev.astype({'item_sku_id':'str'})
    df_dev=df_dev[['item_sku_id','sale_ord_dt','gena_sale_qtty','sale_pre']]
    #计算日均wmape
    df_dev_nation=df_dev.groupby(['item_sku_id','sale_ord_dt']).sum().reset_index()
    df_dev_nation['pred_error']=df_dev_nation.apply(lambda x:abs(x.sale_pre-x.gena_sale_qtty),axis=1)
    df_dev_nation_day_sum=df_dev_nation.groupby(['sale_ord_dt']).sum().reset_index()
    day_mape=mape(df_dev_nation_day_sum.pred_error,df_dev_nation_day_sum.gena_sale_qtty)
    print(day_mape)

    return day_mape
    
df_all = pd.read_csv('raytest.csv')
df_all.dropna(how='any',inplace=True)
no_fea_list=['cate_id']
all_data=df_all.drop(no_fea_list,axis=1)
all_data['sale_ord_dt']=pd.to_datetime(all_data.sale_ord_dt)
max_data=all_data.sale_ord_dt.max()
predict_days=7
test_start_date=pd.to_datetime(max_data) + datetime.timedelta(days=(predict_days*-1))
df_train=all_data[all_data.sale_ord_dt<=test_start_date]
df_dev=all_data[(all_data.sale_ord_dt<=max_data)&(all_data.sale_ord_dt>test_start_date)]
#打乱训练集
df_train=df_train.sample(frac=1)
x_train=df_train.drop(['item_sku_id','sale_ord_dt','gena_sale_qtty'],axis=1)
x_test=df_dev.drop(['item_sku_id','sale_ord_dt','gena_sale_qtty'],axis=1)
y_train=df_train['gena_sale_qtty']
y_test=df_dev['gena_sale_qtty'] 
train_data = lgb.Dataset(x_train, label=y_train)
test_data = lgb.Dataset(x_test, label=y_test)
cat_feature=['big_sale_flag','is_weekday','day_week','week_num',
                                  'mon_num','day_mon','region']
def traindata(config):
    gbm = lgb.train(
        config,
        train_set=train_data,
        valid_sets=[test_data],
        valid_names=["eval"],
        verbose_eval=False,
        categorical_feature=cat_feature
         callbacks=[
             TuneReportCheckpointCallback({
                 "l1": "eval-l1"
             })
         ])
    y_pre=gbm.predict(x_test)
    res=sklearn.metrics.mean_absolute_error(y_pre,y_test)
    tune.report(mean_accuracy=res, done=True)
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--server-address",
        type=str,
        default=None,
        required=False,
        help="The address of server to connect to if using "
        "Ray Client.")
    args, _ = parser.parse_known_args()

    if args.server_address:
        import ray

        ray.init(f"ray://{args.server_address}")

    config = {
        "boosting_type": "gbdt",
        'objective': 'regression',
        "metric": "l1",
        "verbose": -1,
        "learning_rate": tune.grid_search([1e-4, 1e-3, 1e-2]),
        "num_boost_round": tune.grid_search([300, 500, 1000]),
        "colsample_bytree": tune.grid_search([0.7, 0.8,1]),
        "max_depth": tune.grid_search([5, 6, 7]),
    }

    analysis = tune.run(
        traindata,
        metric="l1",
        mode="min",
        config=config,
         num_samples=10,
         scheduler=ASHAScheduler(max_t=200)
        )

    print("Best hyperparameters found were: ", analysis.best_config)

`

**Comment by cgy-dayup** [comment]
> Are you loading the dataset in a distributed fashion? Can you show the entire script?

no,i am not.i load the csv from local.Below is the full script：

import lightgbm as lgb
import numpy as np
import pandas as pd
import datetime
import sklearn.datasets
import sklearn.metrics
from sklearn.model_selection import train_test_split
from ray import tune
from ray.tune.schedulers import ASHAScheduler
from ray.tune.integration.lightgbm import TuneReportCheckpointCallback
from time import *
def mape(error, y):
error=error[y!=0]
y=y[y!=0]
err=np.abs(error/y)
return np.mean(err)
def  cal_mape_nation(df_dev):
if df_dev.dtypes['item_sku_id']=='float':
df_dev=df_dev.astype({'item_sku_id':'int'})
df_dev=df_dev.astype({'item_sku_id':'str'})
df_dev=df_dev[['item_sku_id','sale_ord_dt','gena_sale_qtty','sale_pre']]
df_dev_nation=df_dev.groupby(['item_sku_id','sale_ord_dt']).sum().reset_index()
df_dev_nation['pred_error']=df_dev_nation.apply(lambda x:abs(x.sale_pre-x.gena_sale_qtty),axis=1)
df_dev_nation_day_sum=df_dev_nation.groupby(['sale_ord_dt']).sum().reset_index()
day_mape=mape(df_dev_nation_day_sum.pred_error,df_dev_nation_day_sum.gena_sale_qtty)
     return day_mape
df_all = pd.read_csv('raytest.csv')
df_all.dropna(how='any',inplace=True)
no_fea_list=['cate_id']
all_data=df_all.drop(no_fea_list,axis=1)
all_data['sale_ord_dt']=pd.to_datetime(all_data.sale_ord_dt)
max_data=all_data.sale_ord_dt.max()
predict_days=7
test_start_date=pd.to_datetime(max_data) + datetime.timedelta(days=(predict_days*-1))
df_train=all_data[all_data.sale_ord_dt<=test_start_date]
df_dev=all_data[(all_data.sale_ord_dt<=max_data)&(all_data.sale_ord_dt>test_start_date)]
df_train=df_train.sample(frac=1)
x_train=df_train.drop(['item_sku_id','sale_ord_dt','gena_sale_qtty'],axis=1)
x_test=df_dev.drop(['item_sku_id','sale_ord_dt','gena_sale_qtty'],axis=1)
y_train=df_train['gena_sale_qtty']
y_test=df_dev['gena_sale_qtty']
train_data = lgb.Dataset(x_train, label=y_train)
test_data = lgb.Dataset(x_test, label=y_test)
cat_feature=['big_sale_flag','is_weekday','day_week','week_num',
'mon_num','day_mon','region']
def traindata(config):
gbm = lgb.train(
config,
train_set=train_data,
valid_sets=[test_data],
valid_names=["eval"],
verbose_eval=False,
categorical_feature=cat_feature
callbacks=[
TuneReportCheckpointCallback({
"l1": "eval-l1"
})
])
y_pre=gbm.predict(x_test)
res=sklearn.metrics.mean_absolute_error(y_pre,y_test)
tune.report(mean_accuracy=res, done=True)

if name == "main":
import argparse
parser = argparse.ArgumentParser()
parser.add_argument(
"--server-address",
type=str,
default=None,
required=False,
help="The address of server to connect to if using "
"Ray Client.")
args, _ = parser.parse_known_args()

if args.server_address:
    import ray

    ray.init(f"ray://{args.server_address}")

config = {
    "boosting_type": "gbdt",
    'objective': 'regression',
    "metric": "l1",
    "verbose": -1,
    "learning_rate": tune.grid_search([1e-4, 1e-3, 1e-2]),
    "num_boost_round": tune.grid_search([300, 500, 1000]),
    "colsample_bytree": tune.grid_search([0.7, 0.8,1]),
    "max_depth": tune.grid_search([5, 6, 7]),
}

analysis = tune.run(
    traindata,
    metric="l1",
    mode="min",
    config=config,
     num_samples=10,
     scheduler=ASHAScheduler(max_t=200)
    )

print("Best hyperparameters found were: ", analysis.best_config)

**Comment by cgy-dayup** [comment]
> Are you loading the dataset in a distributed fashion? Can you show the entire script?
no,i am not.i load the csv from local.Below is the full script：

x_test=df_dev.drop(['item_sku_id','sale_ord_dt','gena_sale_qtty'],axis=1)
y_train=df_train['gena_sale_qtty']
y_test=df_dev['gena_sale_qtty'] 
train_data = lgb.Dataset(x_train, label=y_train)
test_data = lgb.Dataset(x_test, label=y_test)
cat_feature=['big_sale_flag','is_weekday','day_week','week_num',
                                  'mon_num','day_mon','region']
def traindata(config):
    gbm = lgb.train(
        config,
        train_set=train_data,
        valid_sets=[test_data],
        valid_names=["eval"],
        verbose_eval=False,
        categorical_feature=cat_feature
         callbacks=[
             TuneReportCheckpointCallback({
                 "l1": "eval-l1"
             })
         ])
    y_pre=gbm.predict(x_test)
    res=sklearn.metrics.mean_absolute_error(y_pre,y_test)
    tune.report(mean_accuracy=res, done=True)
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--server-address",
        type=str,
        default=None,
        required=False,
        help="The address of server to connect to if using "
        "Ray Client.")
    args, _ = parser.parse_known_args()
    if args.server_address:
        import ray
        ray.init(f"ray://{args.server_address}")
    config = {
        "boosting_type": "gbdt",
        'objective': 'regression',
        "metric": "l1",
        "verbose": -1,
        "learning_rate": tune.grid_search([1e-4, 1e-3, 1e-2]),
        "num_boost_round": tune.grid_search([300, 500, 1000]),
        "colsample_bytree": tune.grid_search([0.7, 0.8,1]),
        "max_depth": tune.grid_search([5, 6, 7]),
    }

    analysis = tune.run(
        traindata,
        metric="l1",
        mode="min",
        config=config,
         num_samples=10,
         scheduler=ASHAScheduler(max_t=200)
        )
    print("Best hyperparameters found were: ", analysis.best_config)

**Comment by Yard1** [comment]
In general, you should not be using non-local variables with Ray, and for Tune, data should be passed through `tune.with_parameters`. Try this:

```python
y_train=df_train['gena_sale_qtty']
y_test=df_dev['gena_sale_qtty'] 
cat_feature=['big_sale_flag','is_weekday','day_week','week_num',
                                  'mon_num','day_mon','region']
def traindata(config, x_train, x_test, y_train, y_test):
    train_data = lgb.Dataset(x_train, label=y_train)
    test_data = lgb.Dataset(x_test, label=y_test)
    gbm = lgb.train(
        config,
        train_set=train_data,
        valid_sets=[test_data],
        valid_names=["eval"],
        verbose_eval=False,
        categorical_feature=cat_feature
         callbacks=[
             TuneReportCheckpointCallback({
                 "l1": "eval-l1"
             })
         ])
    y_pre=gbm.predict(x_test)
    res=sklearn.metrics.mean_absolute_error(y_pre,y_test)
    tune.report(mean_accuracy=res, done=True)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--server-address",
        type=str,
        default=None,
        required=False,
        help="The address of server to connect to if using "
        "Ray Client.")
    args, _ = parser.parse_known_args()
    if args.server_address:
        import ray
        ray.init(f"ray://{args.server_address}")
    config = {
        "boosting_type": "gbdt",
        'objective': 'regression',
        "metric": "l1",
        "verbose": -1,
        "learning_rate": tune.grid_search([1e-4, 1e-3, 1e-2]),
        "num_boost_round": tune.grid_search([300, 500, 1000]),
        "colsample_bytree": tune.grid_search([0.7, 0.8,1]),
        "max_depth": tune.grid_search([5, 6, 7]),
    }

    analysis = tune.run(
        tune.with_parameters(traindata, x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test),
        metric="l1",
        mode="min",
        config=config,
         num_samples=10,
         scheduler=ASHAScheduler(max_t=200)
        )
    print("Best hyperparameters found were: ", analysis.best_config)
 ```
 
 If this doesn't work, consider using LightGBM-Ray (you are using regular LightGBM) and pass data through a Ray Dataset.

**Comment by cgy-dayup** [comment]
> 

thank you! i solved the problem after using your method.And i also have a question:
what's the difference between  'tune.report'  and 'TuneReportCheckpointCallback'?i find the ‘ mean_accuracy‘ reported by ’tune.report‘  is not reflected anywhere.
