### ISSUE TITLE
ValueError: cannot find context for 'fork' on windows

### ISSUE THREAD

**Issue by tfgstudios** [ray-project/xgboost_ray#208]
Running this code doesn't work
`
            model = xgboost_ray.train(
                {
                    # This is important to be set correctly for the problem type (multi class in our case)
                    'objective': objective,

                    'eval_metric': self.val_metric,
                    'enable_categorical': enable_categorical,
                    'use_label_encoder': use_label_encoder,
                    'tree_method': tree_method,
                    'max_depth': max_depth,
                    'n_jobs': n_jobs,
                    'learning_rate': learning_rate,
                    'num_parallel_tree': num_parallel_tree,
                    'colsample_bylevel': colsample_bylevel,

                    'sample_weight': weights.train.samples,
                    'sample_weight_eval_set': [weights.val.samples],
                    'feature_weights': weights.flatten_sequence_weights,

                    'min_child_weight': min_child_weight,
                    'gamma': gamma,
                    'reg_alpha': reg_alpha,
                    'reg_lambda': reg_lambda,
                    'max_bin': max_bin,

                    'random_state': random_state,
                    'verbosity': verbosity,
                },
                train_set,
                num_boost_round=num_boost_round,
                evals=[(val_set, 'val')],
                early_stopping_rounds=self.early_stopping_rounds,
                verbose_eval=10,

                # Ray-specific params
                ray_params=RayParams(
                    num_actors=1,
                    cpus_per_actor=max(1, os.cpu_count()-1),
                    gpus_per_actor=-1,
                )
            )`

Tried to set `multiprocessing.set_start_method("spawn", force=True)` before, but it doesn't work

**Comment by amogkam** [comment]
Hey @tfgstudios, thanks for raising this issue! Unfortunately `xgboost-ray` does not work on Windows. We require the `fork` method to be used for multiprocessing instead of `spawn`. 

We will add this as an enhancement to provide support for this in the future!

**Comment by amogkam** [comment]
Going to close this issue, but @tfgstudios please +1 this issue for adding windows support #210!
