### ISSUE TITLE
Deprecation of Ray API

### ISSUE THREAD

**Issue by richardliaw** [ray-project/xgboost_ray#225]
Seeing this on master:

(_RemoteRayXGBoostActor pid=64379) 2022-07-15 15:14:11,494      WARNING __init__.py:193 -- DeprecationWarning: `ray.worker.get_resource_ids` is a private attribute and access will be removed in a future Ray version.

**Comment by amogkam** [comment]
cc @dmatrix- same issue you got

**Comment by dmatrix** [comment]
Yes indeed.

**Comment by pcmoritz** [comment]
Same here, this should be fixed before Ray 2.0 is released!

**Comment by dmatrix** [comment]
I’m getting messages in this notebook in the master in this notebook. 

https://github.com/dmatrix/misc-code/blob/master/py/ray/rayair/ray_air_in_ten_minutes.ipynb
