### ISSUE TITLE
Allow for `qid` to be a column in the dataset

### ISSUE THREAD

**Issue by Yard1** [ray-project/xgboost_ray#237]
Currently we expect `qid` (used in ranking) to be a separate data object passed as an argument to `RayDMatrix`. It would make sense to also allow for an existing column in the dataset to be used for that purpose.

**Comment by Yard1** [comment]
This is already possible.

**Comment by heyitsmui** [comment]
@Yard1 qq - xgboost expect the qid or group to be sorted (on a partition level) before getting passed into dmatrix, as a small enhancement, can we try to support this by using ray data to sort as the data is getting ingested into each worker? cc @atomic

**Comment by Yard1** [comment]
sure, can you open a new issue for that? @heyitsmui

**Comment by heyitsmui** [comment]
@Yard1 opened a ticket for this: https://github.com/ray-project/xgboost_ray/issues/238 and added some comments
