### ISSUE TITLE
Sort qid or group col when ingesting data partition into raydmatrix for ranking

### ISSUE THREAD

**Issue by heyitsmui** [ray-project/xgboost_ray#238]
**Description**
xgboost expect the qid or group to be sorted (on a partition level) before getting passed into dmatrix, as a small enhancement, we can consider using ray data to sort as the data is getting ingested into each worker

**Use case**
Convenience for users doing ranking on xgboost ray

**Comment by heyitsmui** [comment]
cc @atomic

**Comment by heyitsmui** [comment]
@Yard1 this might be an interesting onboarding task for us, do you think @atomic can take this on with some guidance from you?

**Comment by Yard1** [comment]
Yes, that would be great! Happy to help @atomic

**Comment by heyitsmui** [comment]
I believe we can close this since the PR is merged and xgboost 1.11 includes this change. Thanks @Yard1 @atomic !
