### ISSUE TITLE
Can RDMatrix convert to DMatrix? 

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/xgboost_ray#249]
Is there an API to use to convert the two types easily? If so, any examples available?

**Comment by Yard1** [comment]
No, converting a RayDMatrix to a DMatrix would go against the purpose of the former. The RayDMatrix is a wrapper around a data source that is sharded for each worker. Each of the workers then internally initializes a DMatrix from its shard of the data. If you want to modify the actual training code, refer to https://github.com/ray-project/xgboost_ray/issues/248#issuecomment-1340132284

**Comment by Jeffwan** [comment]
@Yard1 Thanks for the details. I will close this one now and let's discuss more details in #248
