### ISSUE TITLE
set_base_margin for RayDMatrix?

### ISSUE THREAD

**Issue by graceyangfan** [ray-project/xgboost_ray#262]
Hello,I am trying to moving some xgboost to ray_xgboost,is there any functions like set_base_margin of DMatrix for RayDMatrix?
xgboost can set it correctly,in RayDMatrix I try to set the base_margin,I always meet error,when xgboost have 2 classes,I set base_margin as array of [len(train),2],but meet ValueError: Data must be 1-dimensional in _split_dataframe

**Comment by Yard1** [comment]
Can you show an end to end example of how you'd do that with xgboost?

**Comment by graceyangfan** [comment]
I am sorry,close this issue
