### ISSUE TITLE
Adding to support to feature_weights

### ISSUE THREAD

**Issue by mozjay0619** [ray-project/xgboost_ray#264]
The current xgboost_ray does not support feature_weights, which I need the support for. 

I implemented the feature_weights support in my personal local branch, which I tested for both _CentralRayDMatrixLoader and _DistributedRayDMatrixLoader (did not add the support for RayDeviceQuantileDMatrix). Is there a way to put in the PR for this branch? I don't seem to have permission to do so.

**Comment by Yard1** [comment]
You should be able to submit a PR - we have not restricted that.

**Comment by mozjay0619** [comment]
You are right. I just submitted the PR (https://github.com/ray-project/xgboost_ray/pull/265) for the new support. Closing this issue.
