### ISSUE TITLE
Worker initialization hook for xgboost workers?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/xgboost_ray#49]
Sometimes it's convenient to be able to run some startup command or initialization code before xgboost workers start. 

For example, setting an env var or doing some data download (dynamically). This would make it easier to do interactive development (as opposed to relying on the cluster bootstrap code to do this).

cc @krfricke

**Comment by krfricke** [comment]
This sounds useful. It probably makes sense to add hooks after training (cleanup) and on training interruption (fault tolerance) as well and do this via a class-based callback system.
