### ISSUE TITLE
Issue on Device Quantile DMatrix.

### ISSUE THREAD

**Issue by trivialfis** [ray-project/xgboost_ray#65]
Hi team, it was mentioned during our offline chat that in some cases the Device Quantile DMatrix doesn't work.  It would be great if there's a description and a reproducible example for the issue so that we can try to fix it.

**Comment by krfricke** [comment]
Hey @trivialfis, thanks for opening this issue. I will investigate this this week/early next week and will get back to you after that!

**Comment by krfricke** [comment]
Hi @trivialfis, I took a look and fixed a couple of incompatibilities in #69. The error was on our end, the DeviceQuantileDMatrix itself seems to work fine.

As stated there I think it makes sense for us to investigate if we can add an interface that loads from files into GPU memory directly. However, this is unrelated to the original question and should be explored in a separate thread.
