### ISSUE TITLE
Revisiting the Queue architecture

### ISSUE THREAD

**Issue by richardliaw** [ray-project/xgboost_ray#7]
In python MP, queues are very light weight -- they can be used without extra thought, just like a standard data structure in python.

In ray, this is very different -- the ray.util.Queue object is an actor on a separate process, which means that queues (and actors, by default) can be placed in arbitrary node of the cluster. 

This by itself leads to a variety of problems:

1. Killing an actor will not kill its corresponding queue (especially if both are created by the driver). This can be a source of resource leakages.

2. Node failures can break multiple queues/actors at once. Imagine a scenario with 50 worker nodes. Since queue actors can be placed anywhere, they can end up being all placed on 1 node. If you kill that 1 node, all other actors/ray executors can be affected.

Thus, we should:

1. try to reduce the number of queue actors used
2. be aware of where we are placing that queue actor.

cc @amogkam @krfricke

**Comment by edoakes** [comment]
cc @architkulkarni

**Comment by krfricke** [comment]
Since the refactor we're down to using one queue for communication. Should we make sure to always place this on the head node?

**Comment by richardliaw** [comment]
Hmm, we should always place it with one of the training actors.

I think we will want to implement colocation with placement groups soon, and then while we do that we will want to make sure the queue actor is on the same node as some of the training workers.

**Comment by amogkam** [comment]
Now that #29 is merged, both points should be fully resolved.
