### ISSUE TITLE
xgboost train appear Task failed: IOError

### ISSUE THREAD

**Issue by KangTomwk** [ray-project/xgboost_ray#98]
Hi：
```
train_dtrain = xgb.DMatrix(actual_dfs.drop(["label"], axis = 1),actual_dfs.label)
config = {
    "tree_method": "hist",
    "eval_metric": ["logloss", "error"],
}
steps = 1
evals_result = dict()
bst = xgb.train(
    config,
    train_dtrain,
    steps,
    evals=[(train_dtrain, "train")],
    evals_result=evals_result) 
```

I perform xgboost training, the data volume is added to 100W, and the master has been stuck, and the following error appears in the python-core-driver-xxx.log：

task_manager.cc:323: Task failed: IOError: 8: Sent message larger than max (141176840 vs. 104857600): Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=modin.experimental.xgboost.xgboost_ray, class_name=ModinXGBoostActor, function_name=set_train_data, function_hash=}, task_id=b37e32bac24e65b94b070e4001000000, task_name=ModinXGBoostActor.set_train_data(), job_id=01000000, num_args=25602, num_returns=2, actor_task_spec={actor_id=4b070e4001000000, actor_caller_id=ffffffffffffffffffffffff01000000, actor_counter=0} 

Has anyone encountered it? ? ? How to solve it? ?

**Comment by richardliaw** [comment]
Can you provide a script that we can run @KangTomwk ?

**Comment by krfricke** [comment]
Hi @KangTomwk,

this actually looks like you're using Modin's XGBoost implementation (https://modin.readthedocs.io/en/latest/modin_xgboost.html) and not XGBoost-Ray.

For examples on how to use XGBoost-Ray (the `xgboost_ray` package), please take a look at our [readme](https://github.com/ray-project/xgboost_ray). It should be straightforward to convert your code to use xgboost_ray.

Something like this should work:

```
from xgboost_ray import RayDMatrix, RayParams, train

train_dtrain = RayDMatrix(actual_dfs.drop(["label"], axis = 1), actual_dfs.label)

config = {
    "tree_method": "hist",
    "eval_metric": ["logloss", "error"],
}
steps = 1
evals_result = dict()
bst = train(
    config,
    train_dtrain,
    steps,
    evals=[(train_dtrain, "train")],
    evals_result=evals_result,
    ray_params=RayParams(
        num_actors=2,
        cpus_per_actor=1))) 
```

**Comment by KangTomwk** [comment]
> Hi @KangTomwk,
> 
> this actually looks like you're using Modin's XGBoost implementation (https://modin.readthedocs.io/en/latest/modin_xgboost.html) and not XGBoost-Ray. Note that these are different projects - XGBoost-Ray provides a general interface for distributed XGBoost training on Ray, and Modin is just one of our supported data sources.
> 
> For examples on how to use XGBoost-Ray (the `xgboost_ray` package), please take a look at our [readme](https://github.com/ray-project/xgboost_ray). It should be straightforward to convert your code to use xgboost_ray.
> 
> Something like this should work:
> 
> ```
> from xgboost_ray import RayDMatrix, RayParams, train
> 
> train_dtrain = RayDMatrix(actual_dfs.drop(["label"], axis = 1), actual_dfs.label)
> 
> config = {
>     "tree_method": "hist",
>     "eval_metric": ["logloss", "error"],
> }
> steps = 1
> evals_result = dict()
> bst = train(
>     config,
>     train_dtrain,
>     steps,
>     evals=[(train_dtrain, "train")],
>     evals_result=evals_result,
>     ray_params=RayParams(
>         num_actors=2,
>         cpus_per_actor=1))) 
> ```

Hi 
Because my actual_dfs is a modin dataframe, it is problematic to directly use the RayDMatrix method of xgboost_ray！！！

**Comment by krfricke** [comment]
XGBoost-Ray supports Modin dataframes, if there's an error, can you please report it?

If you'd like stick with Modin's XGBoost implementation we cannot help however, you'll have to raise the issue on their tracker.

**Comment by krfricke** [comment]
I'm closing this for now since it's unrelated to XGBoost-Ray. Feel free to reach out if you need help setting your experiment up with XGBoost-Ray.
